// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1BUKJa9-F3MAnGAnRhI3ILp4RMe6Kub8',
    appId: '1:604035445374:web:52011d322d5d567b329e2f',
    messagingSenderId: '604035445374',
    projectId: 'fir-series-2560d',
    authDomain: 'fir-series-2560d.firebaseapp.com',
    storageBucket: 'fir-series-2560d.firebasestorage.app',
    measurementId: 'G-Y1R3EMJ44S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YGYoIeX7GTOF0qKzv21UNpe1u3uf-wE',
    appId: '1:604035445374:android:816da7c0cd5c808c329e2f',
    messagingSenderId: '604035445374',
    projectId: 'fir-series-2560d',
    storageBucket: 'fir-series-2560d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkCnVUCFynIezhxayzOYHtPe7iglXmo7I',
    appId: '1:604035445374:ios:a510de6df19d6568329e2f',
    messagingSenderId: '604035445374',
    projectId: 'fir-series-2560d',
    storageBucket: 'fir-series-2560d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );
}
